//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.Guid Id { get; set; }
        public System.Guid Teacher { get; set; }
    }
}
